FROM renatbek/activator:1.3.10
MAINTAINER Renat Bekbolatov <renatbek@gmail.com>

COPY ./ /app/.

RUN mkdir -p /var/lib/starpractice/activity
COPY activity /var/lib/starpractice/activity/.

EXPOSE 9000 
WORKDIR /app
#CMD ["activator", "run"]

