set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-sensible'
"Plugin 'wincent/command-t'
Plugin 'myusuf3/numbers.vim'
Plugin 'kien/rainbow_parentheses.vim'
"Plugin 'powerline/powerline'

Plugin 'flazz/vim-colorschemes'
Plugin 'derekwyatt/vim-scala'

call vundle#end()            " required

filetype plugin indent on    " required


" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

nnoremap <space> :NumbersToggle<CR>:set paste<CR>


set nu
set ignorecase

set tabstop=2
set shiftwidth=4
set expandtab
set autoindent
set smarttab
set smartcase

syntax on
colorscheme candy

set statusline+=%F\ %l\:%c
set ruler
set modeline
set ls=2

set paste
set scroll=1

au BufNewFile,BufRead *.repl setlocal ft=scala


